###
POST http://localhost:8080/api/albums
Content-Type: application/json

{
  "id": 1,
  "name": "Meteora",
  "genre": "Rock",
  "artistId": "1"
}

###
GET http://localhost:8080/api/albums

###
GET http://localhost:8080/api/albums/1

###
PUT http://localhost:8080/api/albums/1
Content-Type: application/json

{
  "id": 1,
  "name": "Meteora (20th Anniversary)",
  "genre": "Alternative Rock",
  "artistId": "1"
}

###
DELETE http://localhost:8080/api/albums/1

###
DELETE http://localhost:8080/api/albums